#!/usr/bin/env bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

compile() {
    mkdir -p build
    cc -o ./nob/nob ./nob/nob.c
    ./nob/nob
}

run() {
    ./build/main
}

help() {
    echo "$ dev compile : compile project"
    echo "$ dev run     : run compiled binary"
    echo "$ dev         : compile/run"
    echo "$ dev help    : display help"
}

case "$1" in
  compile)
    compile
    ;;
  run)
    build
    run
    ;;
  help)
    help
    ;;
  *)
    build
    run
    ;;
esac
